# Generated by Django 4.2.6 on 2023-10-07 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('city', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('phone_number', models.IntegerField()),
                ('gender', models.CharField(max_length=6)),
                ('color', models.CharField(default='', max_length=10)),
                ('case', models.CharField(max_length=200)),
                ('code', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('paid_amount', models.IntegerField()),
                ('monthly_rent', models.IntegerField(blank=True, null=True)),
                ('next_appointment_date', models.DateField(blank=True, null=True)),
                ('next_appointment_time', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatientVisits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited_date', models.DateField()),
                ('paid_amount', models.IntegerField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='api.patientdata')),
            ],
        ),
        migrations.CreateModel(
            name='PatientImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.patientdata')),
            ],
        ),
    ]
