# Generated by Django 4.2.6 on 2023-10-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdata',
            name='color',
            field=models.CharField(max_length=10),
        ),
    ]
