# Generated by Django 4.2.6 on 2023-10-08 13:47

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_patientdata_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdata',
            name='visits',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='patientimages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_to_this_patient_folder),
        ),
        migrations.DeleteModel(
            name='PatientVisits',
        ),
    ]
